M48
; DRILL file {KiCad 8.0.6} date 2026-08-05T21:55:56+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-05T21:55:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
%
G90
G05
T2
X78.165Y-51.32
T1
X78.165Y-44.03G85X78.165Y-43.61
G05
M30
