M48
; DRILL file {KiCad 8.0.6} date 2026-07-29T17:27:28+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-29T17:27:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
%
G90
G05
T2
X3.0774Y-2.0205
T1
G00X3.0774Y-1.7335
M15
G01X3.0774Y-1.7169
M16
G05
M30
